1. ÚVOD
2. CELKOVÁ HRA
3. NÁPAD (BLOODBORNE A JUMP KING)
4. ROZDĚLENÍ (MATY - GRAFIKA + MAPA + SCENE MANAGER + MENU; VIKTOR - FYZIKA + COLLIDERS + MANAGER + MOVEMENT; KAMIL - STORY + VOICELINES + SFX + CUTSCENES + BOSS + STATS)
4.5 VKM VIKINGS 
5. DEVELOPMENT (ZAČÁTEK)
6. DEVELOPMENT (MID)
7. DEVELOPMENT (KONEC + NO TIME)
8. DEVELOPMENT (CUT FEATURES)
9. EXPERIENCE
10. BEST OF/FUNNY SHIT (69 commits + custom memes)
11. ZDROJE 
